#!/bin/bash
# This is a script that prints the absolute path of the current working directory.
# Usage: ./0-current_working_directory

# Using the pwd command to print the absolute path of the current working directory
current_directory=$(pwd)
echo "Absolute path of the current working directory: $current_directory"
